Repository readmeio/httpsnippet, pull requests merged in 2021-02, with the labels that each got.

#34 feat: extending the useObjectBody option to JS fetch()
  README.md
  src/targets/javascript/fetch.js
  src/targets/node/fetch.js
  test/fixtures/output/javascript/fetch/application-form-encoded.js
  test/fixtures/output/javascript/fetch/application-json.js
  test/fixtures/output/javascript/fetch/cookies.js
  test/fixtures/output/javascript/fetch/custom-method.js
  test/fixtures/output/javascript/fetch/full.js
  test/fixtures/output/javascript/fetch/headers.js
  test/fixtures/output/javascript/fetch/https.js
  test/fixtures/output/javascript/fetch/jsonObj-multiline.js
  test/fixtures/output/javascript/fetch/jsonObj-null-value.js
  test/fixtures/output/javascript/fetch/multipart-data.js
  test/fixtures/output/javascript/fetch/multipart-file.js
  test/fixtures/output/javascript/fetch/multipart-form-data.js
  test/fixtures/output/javascript/fetch/query.js
  test/fixtures/output/javascript/fetch/short.js
  test/fixtures/output/javascript/fetch/text-plain.js
  test/fixtures/output/node/fetch/application-form-encoded.js
  test/fixtures/output/node/fetch/application-json.js
  test/fixtures/output/node/fetch/cookies.js
  test/fixtures/output/node/fetch/custom-method.js
  test/fixtures/output/node/fetch/full.js
  test/fixtures/output/node/fetch/headers.js
  test/fixtures/output/node/fetch/https.js
  test/fixtures/output/node/fetch/jsonObj-multiline.js
  test/fixtures/output/node/fetch/jsonObj-null-value.js
  test/fixtures/output/node/fetch/multipart-data.js
  test/fixtures/output/node/fetch/multipart-file.js
  test/fixtures/output/node/fetch/multipart-form-data.js
  test/fixtures/output/node/fetch/query.js
  test/fixtures/output/node/fetch/short.js
  test/fixtures/output/node/fetch/text-plain.js
  test/targets/javascript/fetch.js
  test/targets/node/fetch.js
Labels: type:bug, type:enhancement

#33 feat: adding an option for disabling query string encoding
  README.md
  src/index.js
  test/fixtures/output/c/libcurl/query-encoded.c
  test/fixtures/output/clojure/clj_http/query-encoded.clj
  test/fixtures/output/csharp/httpclient/query-encoded.cs
  test/fixtures/output/csharp/restsharp/query-encoded.cs
  test/fixtures/output/go/native/query-encoded.go
  test/fixtures/output/http/1.1/query-encoded
  test/fixtures/output/java/asynchttp/query-encoded.java
  test/fixtures/output/java/nethttp/query-encoded.java
  test/fixtures/output/java/okhttp/query-encoded.java
  test/fixtures/output/java/unirest/query-encoded.java
  test/fixtures/output/javascript/axios/query-encoded.js
  test/fixtures/output/javascript/fetch/query-encoded.js
  test/fixtures/output/javascript/jquery/query-encoded.js
  test/fixtures/output/javascript/xhr/query-encoded.js
  test/fixtures/output/kotlin/okhttp/query-encoded.kt
  test/fixtures/output/node/axios/query-encoded.js
  test/fixtures/output/node/fetch/query-encoded.js
  test/fixtures/output/node/native/query-encoded.js
  test/fixtures/output/node/request/query-encoded.js
  test/fixtures/output/node/unirest/query-encoded.js
  test/fixtures/output/objc/nsurlsession/query-encoded.m
  test/fixtures/output/ocaml/cohttp/query-encoded.ml
  test/fixtures/output/php/curl/query-encoded.php
  test/fixtures/output/php/http1/query-encoded.php
  test/fixtures/output/php/http2/query-encoded.php
  test/fixtures/output/powershell/restmethod/query-encoded.ps1
  test/fixtures/output/powershell/webrequest/query-encoded.ps1
  test/fixtures/output/python/python3/query-encoded.py
  test/fixtures/output/python/requests/query-encoded.py
  test/fixtures/output/r/httr/query-encoded.r
  test/fixtures/output/ruby/native/query-encoded.rb
  test/fixtures/output/shell/curl/query-encoded.sh
  test/fixtures/output/shell/httpie/query-encoded.sh
  test/fixtures/output/shell/wget/query-encoded.sh
  test/fixtures/output/swift/nsurlsession/query-encoded.swift
  test/fixtures/requests/query-encoded.json
  test/targets.js
Labels: type:enhancement

#36 switch ruby ssl from verify_none to verify_peer
  package-lock.json
  package.json
  src/targets/ruby/native.js
  test/fixtures/output/ruby/native/https.rb
Labels: type:bug
